window.RISK_PHRASES =
  "1": "Explosivt i torrt tillstånd"
  "2": "Explosivt vid stöt, friktion, eld eller annan antändningsorsak"
  "3": "Mycket explosivt vid stöt, friktion, eld eller annan antändningsorsak"
  "4": "Bildar mycket känsliga explosiva metallföreningar"
  "5": "Explosivt vid uppvärmning"
  "6": "Explosivt vid kontakt och utan kontakt med luft"
  "7": "Kan orsaka brand"
  "8": "Kontakt med brännbart material kan orsaka brand"
  "9": "Explosivt vid blandning med brännbart material"
  "10": "Brandfarligt"
  "11": "Mycket brandfarligt"
  "12": "Extremt brandfarligt"
  "14": "Reagerar häftigt med vatten"
  "15": "Vid kontakt med vatten bildas extremt brandfarliga gaser"
  "16": "Explosivt vid blandning med oxiderande ämnen"
  "17": "Självantänder i luft"
  "18": "Vid användning kan brännbara/explosiva ång-luftblandningar bildas"
  "19": "Kan bilda explosiva peroxider"
  "20": "Farligt vid inandning"
  "21": "Farligt vid hudkontakt"
  "22": "Farligt vid förtäring"
  "23": "Giftigt vid inandning"
  "24": "Giftigt vid hudkontakt"
  "25": "Giftigt vid förtäring"
  "26": "Mycket giftigt vid inandning"
  "27": "Mycket giftigt vid hudkontakt"
  "28": "Mycket giftigt vid förtäring"
  "29": "Utvecklar giftig gas vid kontakt med vatten"
  "30": "Kan bli mycket brandfarligt vid användning"
  "31": "Utvecklar giftig gas vid kontakt med syra"
  "32": "Utvecklar mycket giftig gas vid kontakt med syra"
  "33": "Kan ansamlas i kroppen och ge skador"
  "34": "Frätande"
  "35": "Starkt frätande"
  "36": "Irriterar ögonen"
  "37": "Irriterar andningsorganen"
  "38": "Irriterar huden"
  "39": "Risk för mycket allvarliga bestående hälsoskador"
  "40": "Misstänks kunna ge cancer"
  "41": "Risk för allvarliga ögonskador"
  "42": "Kan ge allergi vid inandning"
  "43": "Kan ge allergi vid hudkontakt"
  "44": "Explosionsrisk vid uppvärmning i sluten behållare"
  "45": "Kan ge cancer"
  "46": "Kan ge ärftliga genetiska skador"
  "48": "Risk för allvarliga hälsoskador vid långvarig exponering"
  "49": "Kan ge cancer vid inandning"
  "50": "Mycket giftigt för vattenlevande organismer"
  "51": "Giftigt för vattenlevande organismer"
  "52": "Skadligt för vattenlevande organismer"
  "53": "Kan orsaka skadliga långtidseffekter i vattenmiljön"
  "54": "Giftigt för växter"
  "55": "Giftigt för djur"
  "56": "Giftigt för marklevande organismer"
  "57": "Giftigt för bin"
  "58": "Kan orsaka skadliga långtidseffekter i miljön"
  "59": "Farligt för ozonskiktet"
  "60": "Kan ge nedsatt fortplantningsförmåga"
  "61": "Kan ge fosterskador"
  "62": "Möjlig risk för nedsatt fortplantningsförmåga"
  "63": "Möjlig risk för fosterskador"
  "64": "Kan skada spädbarn under amningsperioden"
  "65": "Farligt: kan ge lungskador vid förtäring"
  "66": "Upprepad kontakt kan ge torr hud eller hudsprickor"
  "67": "Ångor kan göra att man blir dåsig och omtöcknad"
  "68": "Möjlig risk för bestående hälsoskador"

  "14/15": "Reagerar häftigt med vatten varvid extremt brandfarliga gaser bildas"
  "15/29": "Utvecklar giftig och extremt brandfarlig gas vid kontakt med vatten"
  "20/21": "Farligt vid inandning och hudkontakt"
  "20/22": "Farligt vid inandning och förtäring"
  "20/21/22": "Farligt vid inandning, hudkontakt och förtäring"
  "21/22": "Farligt vid hudkontakt och förtäring"
  "23/24": "Giftigt vid inandning och hudkontakt"
  "23/25": "Giftigt vid inandning och förtäring"
  "23/24/25": "Giftigt vid inandning, hudkontakt och förtäring"
  "24/25": "Giftigt vid hudkontakt och förtäring"
  "26/27": "Mycket giftigt vid inandning och hudkontakt"
  "26/28": "Mycket giftigt vid inandning och förtäring"
  "26/27/28": "Mycket giftigt vid inandning, hudkontakt och förtäring"
  "27/28": "Mycket giftigt vid hudkontakt och förtäring"
  "36/37": "Irriterar ögonen och andningsorganen"
  "36/38": "Irriterar ögonen och huden"
  "36/37/38": "Irriterar ögonen, andningsorganen och huden"
  "37/38": "Irriterar andningsorganen och huden"
  "39/23": "Giftigt: risk för mycket allvarliga bestående hälsoskador vid inandning"
  "39/24": "Giftigt: risk för mycket allvarliga bestående hälsoskador vid hudkontakt"
  "39/25": "Giftigt: risk för mycket allvarliga bestående hälsoskador vid förtäring"
  "39/23/24": "Giftigt: risk för mycket allvarliga bestående hälsoskador vid inandning och hudkontakt"
  "39/23/25": "Giftigt: risk för mycket allvarliga bestående hälsoskador vid inandning och förtäring"
  "39/24/25": "Giftigt: risk för mycket allvarliga bestående hälsoskador vid hudkontakt och förtäring"
  "39/23/24/25": "Giftigt: risk för mycket allvarliga bestående hälsoskador vid inandning, hudkontakt och förtäring"
  "39/26": "Mycket giftigt: risk för mycket allvarliga bestående hälsoskador vid inandning"
  "39/27": "Mycket giftigt: risk för mycket allvarliga bestående hälsoskador vid hudkontakt"
  "39/28": "Mycket giftigt: risk för mycket allvarliga bestående hälsoskador vid förtäring"
  "39/26/27": "Mycket giftigt: risk för mycket allvarliga bestående hälsoskador vid inandning och hudkontakt"
  "39/26/28": "Mycket giftigt: risk för mycket allvarliga bestående hälsoskador vid inandning och förtäring"
  "39/27/28": "Mycket giftigt: risk för mycket allvarliga bestående hälsoskador vid hudkontakt och förtäring"
  "39/26/27/28": "Mycket giftigt: risk för mycket allvarliga bestående hälsoskador vid inandning, hudkontakt och förtäring"
  "42/43": "Kan ge allergi vid inandning och hudkontakt"
  "48/20": "Farligt: risk för allvarliga hälsoskador vid långvarig exponering genom inandning"
  "48/21": "Farligt: risk för allvarliga hälsoskador vid långvarig exponering genom hudkontakt"
  "48/22": "Farligt: risk för allvarliga hälsoskador vid långvarig exponering genom förtäring"
  "48/20/21": "Farligt: risk för allvarliga hälsoskador vid långvarig exponering genom inandning och hudkontakt"
  "48/20/22": "Farligt: risk för allvarliga hälsoskador vid långvarig exponering genom inandning och förtäring"
  "48/21/22": "Farligt: risk för allvarliga hälsoskador vid långvarig exponering genom hudkontakt och förtäring"
  "48/20/21/22": "Farligt: risk för allvarliga hälsoskador vid långvarig exponering genom inandning, hudkontakt och förtäring"
  "48/23": "Giftigt: risk för allvarliga hälsoskador vid långvarig exponering genom inandning"
  "48/24": "Giftigt: risk för allvarliga hälsoskador vid långvarig exponering genom hudkontakt"
  "48/25": "Giftigt: risk för allvarliga hälsoskador vid långvarig exponering genom förtäring"
  "48/23/24": "Giftigt: risk för allvarliga hälsoskador vid långvarig exponering genom inandning och hudkontakt"
  "48/23/25": "Giftigt: risk för allvarliga hälsoskador vid långvarig exponering genom inandning och förtäring"
  "48/24/25": "Giftigt: risk för allvarliga hälsoskador vid långvarig exponering genom hudkontakt och förtäring"
  "48/23/24/25": "Giftigt: risk för allvarliga hälsoskador vid långvarig exponering genom inandning, hudkontakt och förtäring"
  "50/53": "Mycket giftigt för vattenlevande organismer, kan orsaka skadliga långtidseffekter i vattenmiljön"
  "51/53": "Giftigt för vattenlevande organismer, kan orsaka skadliga långtidseffekter i vattenmiljön"
  "52/53": "Skadligt för vattenlevande organismer, kan orsaka skadliga långtidseffekter i vattenmiljön"
  "68/20": "Farligt: möjlig risk för bestående hälsoskador vid inandning"
  "68/21": "Farligt: möjlig risk för bestående hälsoskador vid hudkontakt"
  "68/22": "Farligt: möjlig risk för bestående hälsoskador vid förtäring"
  "68/20/21": "Farligt: möjlig risk för bestående hälsoskador vid inandning och hudkontakt"
  "68/20/22": "Farligt: möjlig risk för bestående hälsoskador vid inandning och förtäring"
  "68/21/22": "Farligt: möjlig risk för bestående hälsoskador vid hudkontakt och förtäring"
  "68/20/21/22": "Farligt: möjlig risk för bestående hälsoskador vid inandning, hudkontakt och förtäring"